services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: pc_clone_db
      NODE_ENV: development
      PORT: 5011
      REDIS_URL: redis://redis:6379
    ports:
      - "5011:5011"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/app/backend
          ignore:
            - node_modules
        - action: sync
          path: ./packages
          target: /usr/src/app/packages
          ignore:
            - node_modules
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5012:5012"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/app/frontend
          ignore:
            - node_modules
        - action: sync
          path: ./packages
          target: /usr/src/app/packages
          ignore:
            - node_modules
    depends_on:
      - backend

volumes:
  db_data:
  redis_data:
