services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: pc_clone_db
      NODE_ENV: development
      PORT: 5011
    ports:
      - "5011:5011"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/app
          ignore:
            - node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5012:5012"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/app
          ignore:
            - node_modules

volumes:
  db_data:
