services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "(mysqladmin ping -u pingtest || exit 1) && sleep 1"]
      interval: 5s
      retries: 20
      start_interval: 5s
      start_period: 10s

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 20
      start_interval: 5s

  backend:
    build:
      context: .
      dockerfile: ./backend/DockerfileDeploy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: pc_clone_db
      NODE_ENV: production
      PORT: 5011
      REDIS_URL: redis://redis:6379
    ports:
      - "127.0.0.1:5011:5011"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5011/api/health"]
      interval: 5s
      retries: 20
      start_interval: 5s

  frontend:
    build:
      context: .
      dockerfile: ./frontend/DockerfileDeploy
    ports:
      - "5012:5012"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5012"]
      interval: 5s
      retries: 20
      start_interval: 5s

volumes:
  db_data:
  redis_data:
